
org.gradle.jvmargs=-Xmx2048m --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED
android.useAndroidX=true
android.enableJetifier=true
kapt.use.worker.api=false
# Harden Kotlin/Gradle on Windows to avoid file lock issues with memory-mapped caches
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process
